# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab371f3ea10e3d62b16b8edd4a0621eb583522365897a29d159a6d0e6ade8c08b29a9fd8bb9fb88a951671dc6339b3f75ec6e27678bfd5c52d66067b4db92715

test:
  secret_key_base: 6c77e463cade05429b27b6f13c6b98d96fdd8d9fcf11d5f11c611ca6b660675831086b639541bc0fd6cc8779ef246154d87c0d9a93b72770c9556c1e7ea120de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
